# run Black Code Formatter on python modules
name : black_code
on : 
  push: 
    paths:
      - './*.py'
      - '*/*.py'
      - '*/*.py'
      - '*/*/*.py'
      - '*/*/*/*.py'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Analyze code with black
        uses: psf/black@stable
        with:
          args: black -S
