# run Black Code Formatter on python modules
name : black_code
on : 
  push: 
    paths:
      - '**.py'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@stable
      - name: Analyze code with black
        run: black -S
