# run Black Code Formatter on python modules
name : black_code
on : [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@stable
      - name: Analyze the code
        run: |
          black -S --color `ls ./ |grep .py$|xargs`
          black -S --color `ls -d */* |grep .py$|xargs`
          black -S --color `ls -d */*/* |grep .py$|xargs`
          black -S --color `ls -d */*/*/* |grep .py$|xargs`
