# This file builds and runs a lightweight version of the MDTF test suite.
# Note that the tests assess functionality of the diagnostics,
# and do not evaluate data or scientific content.
name: MDTF_test

on:
  push:
    branches:
      - main
      - develop
      - feature/github_actions_workflow
defaults:
  run:
    shell: bash -l {0}
jobs:
  build:
    runs-on: ${{matrix.os}}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        conda-root: [/usr/share/miniconda3, /Users/runner/miniconda3]
        json-file: ["tests/github_actions_test.jsonc","tests/github_actions_test_macos.jsonc"]
        # allow other jobs to run if one fails
        experimental: [false]
        exclude:
          - os: ubuntu-latest
            conda-root: /Users/runner/miniconda3
          - os: ubuntu-latest
            json-file: "tests/github_actions_test_macos.jsonc"
          - os: macos-latest
            conda-root: /usr/share/miniconda3
          - os: macos-latest
            json-file: "tests/github_actions_test.jsonc"
          - conda-root: /usr/share/miniconda3
            json-file: "tests/github_actions_test_macos.jsonc"
          - conda-root: /Users/runner/minconda3
            json-file: "tests/github_actions_test.jsonc"
      max-parallel: 2
    steps:
    - uses: actions/checkout@v2
    - name: Download Miniconda 3
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        python-version: 3.8
    - name: Verify miniconda
      run: |
        conda info -a
    - name: Install XQuartz if macOS
      if: ${{ matrix.os == 'macos-latest' && matrix.conda-root == '/Users/runner/miniconda3' }}
      run: |
        echo "Installing XQuartz"
        brew install --cask xquartz
    - name: Install Conda Environments
      run: |
        echo "Installing Conda Environments"
        # MDTF-specific setup: install all conda envs
        ./src/conda/conda_env_setup.sh -e base --conda_root ${{matrix.conda-root}}
        ./src/conda/conda_env_setup.sh -e synthetic_data --conda_root ${{matrix.conda-root}}
    - name: Get Observational Data
      run: |
        echo "Available Space"
        df -h
        # attempt FTP data fetch
        # allow 20 min for transfer before timeout; Github actions allows 6 hours for individual
        # jobs, but we don't want to max out resources that are shared by the NOAA-GFDL repos.
        curl --verbose --ipv4 --connect-timeout 8 --max-time 1200 --retry 128 --ftp-ssl --disable-epsv --ftp-pasv -u "anonymous:anonymous" ftp://ftp.gfdl.noaa.gov/pub/jessica.liptak/example_obs_data.tar --output example_obs_data.tar
        curl --verbose --ipv4 --connect-timeout 8 --max-time 1200 --retry 128 --ftp-ssl --disable-epsv --ftp-pasv -u "anonymous:anonymous" ftp://ftp.gfdl.noaa.gov/pub/jessica.liptak/convective_transition_diag_obs_data.tar --output convective_transition_diag_obs_data.tar
        #tar -xvf travis_test.tar -C ${PWD}/../ #GH actions double nests the MDTF_diagnostics repo
        ## make input data directories
        #./MDTF-diagnostics/tests/make_test_input_data_dir.sh
        cd ../
        mkdir inputdata
        echo "Untarring test files"
        tar -xvf example_obs_data.tar -C inputdata
        tar -xvf convective_transition_diag_obs_data.tar -C inputdata
        ls -R inputdata
    - name: Generate Model Data
        # clone the mdtf_test_data repo
        git clone https://github.com/jkrasting/mdtf_test_data.git
        # Defining dependencies in Conda env is faster than pip
        conda activate _env_synthetic_data
        # install the test data software
        pushd mdtf_test_data
        pip install .
        # generate the data
        ./scripts/gfdl_synthetic.py
        ./scripts/ncar_synthetic.py
        popd
        mkdir wkdir
        ls */*
        # Check paths relative to MDTF_diagnostics
        cd MDTF-diagnostics
        echo "Diretories one level up"
        ls -R ../*
        echo "Directories and files in the current directory:"
        ls # debug
        echo "Available Space"
        df -h # Log space remaining
    - name: Set environment variables
      run: |
        echo "POD_OUTPUT=$(echo $PWD/../wkdir/MDTF_NCAR-CAM5.timeslice_2000_2003)" >> $GITHUB_ENV
    - name: Run diagnostic tests
      run: |
        echo "POD_OUTPUT is: "
        echo "${POD_OUTPUT}"
        conda activate _MDTF_base
        cat ./mdtf
        # trivial check that install script worked
        ./mdtf --version
        # run the test PODs
        ./mdtf -v -f ${{matrix.json-file}}

    - name: Run unit tests
      run: |
        conda activate _MDTF_base
        git submodule init
        git submodule update
        python -m unittest discover

